---
- name: Playbook to install chrome
#  hosts: localhost
#  hosts: 172.31.29.129
  hosts: kslave1
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list

  tasks:
    - name: verify if chrome already exist
      command: test -f {{ apt_file }}
      register: chrome_apt_exists
      ignore_errors: true

    - debug: msg="{{ chrome_apt_exists }}"

    - name: download chrome
      shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      when: chrome_apt_exists.rc == 1

#     - name: install chrome
#       shell: sudo apt install ./google-chrome-stable_current_amd64.deb
#       when: chrome_apt_exists.rc == 1

#     - name: install chromium
#       apt:
#         name: chromium
#         state: present

#     - name: install chromedriver
#       apt:
#         name: chromedriver
#         state: present

    - name: install chromedriver
      shell: wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
      register: chrome_driver_install

    - debug: msg="{{ chrome_driver_install }}"
    
    - name: unzip chromedriver
      ansible.builtin.unarchive: 
        src: /home/edureka/chromedriver_linux64.zip
        dest: /home/edureka/Documents
        register: chrome_driver_unzip
        remote_src: yes

    - debug: msg="{{ chrome_driver_unzip }}"

#     - name: unzip chromedriver
#       shell: unzip chromedriver_linux64.zip
#       chdir: /home/edureka/Documents
#       register: chrome_driver_unzip

#     - debug: msg="{{ chrome_driver_unzip }}"
    
#     - name: copy chromedriver to documents
#       shell: cp ./chromedriver /home/edureka/Documents
#       register: chrome_driver_cp
#       ignore_errors: true

#     - debug: msg="{{ chrome_driver_cp }}"
