---
- name: Playbook to install chrome
  hosts: kslave1
  become: yes
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list

  tasks:

#     - name: add chrome key
#       shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

#     - name: add chrome repo
#       shell: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> {{ apt_file }}'

    - name: apt update
      shell: sh -c 'apt update'

#     - name: add chrome repo
#       copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{ apt_file }} owner=edureka mode=644

#     - name: update apt cache
#       apt: update_cache=yes

#     - name: install Google Chrome
#       apt: pkg=google-chrome-stable state=present

    - name: download chrome
      shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: install chrome
      shell: apt install ./google-chrome-stable_current_amd64.deb
