---
- name: Playbook to install chrome
  hosts: localhost
#  hosts: kslave1
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list

  tasks:
    - name: verify if chrome already exist
      command: test -f
      register: chrome_apt_exists
      ignore_errors: true

    - debug: msg="{{ chrome_apt_exists }}"

#     - name: add chrome key
#       shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#       when: chrome_apt_exists.rc == 1

#     - name: add chrome repo
#       copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest= owner=root group=root mode=644
#       when: chrome_apt_exists.rc == 1

#     - name: update apt cache
#       apt: update_cache=yes
#       when: chrome_apt_exists.rc == 1

#    - name: install Google Chrome
#      apt: pkg=google-chrome-stable state=installed

