---
- name: Playbook to install chrome
  hosts: localhost
#  hosts: kslave1
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list

  tasks:
    - name: verify if chrome already exist
      command: test -f
      register: chrome_apt_exists
      ignore_errors: true

    - debug: msg="{{ chrome_apt_exists }}"

    - name: download chrome
      shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      when: chrome_apt_exists.rc == 1

#     - name: install chrome
#       shell: sudo apt install ./google-chrome-stable_current_amd64.deb
#       when: chrome_apt_exists.rc == 1

#     - name: install chromium
#       apt:
#         name: chromium
#         state: present

#     - name: chromedriver
#       apt:
#         name: chromedriver
#         state: present
