---
- name: Puppet agent install on slave machine
  hosts: all

  tasks:
#     - name: run as sudo
#       shell: >
#         sudo su -
#       register: sudo_result

#     - debug: msg="{{ sudo_result }}"

    - name: set source
      shell: >
        sudo -s source /etc/profile.d/puppet-agent.sh
      register: source_result

    - debug: msg="{{ source_result }}"

    - name: export path
      shell: >
        sudo -s export PATH=/opt/puppetlabs/bin:$PATH
      register: export_path_result

    - debug: msg="{{ export_path_result }}"
    
    - name: puppet version
      shell: >
        /opt/puppetlabs/bin/puppet -V
      register: puppet_version

    - debug: msg="{{ puppet_version }}"

    - name: set config
      shell: >
        /opt/puppetlabs/bin/puppet config set server kmaster --section main
      register: set_config_result

    - debug: msg="{{ set_config_result }}"
    
#     - name: set config from file
#       shell: >
#         sudo cat ./configfile.txt > /etc/puppetlabs/puppet/puppet.conf
#       #  sudo echo "[main]\nserver = kmaster\n\# This file can be used to override the default puppet settings.\n\# See the following links for more details on what settings are available:\n\# - https://puppet.com/docs/puppet/latest/config_important_settings.html\n\# - https://puppet.com/docs/puppet/latest/config_about_settings.html\n\# - https://puppet.com/docs/puppet/latest/config_file_main.html\n\# - https://puppet.com/docs/puppet/latest/configuration.html" > /etc/puppetlabs/puppet/puppet.conf
#       register: set_config_from_file_result

#     - debug: msg="{{ set_config_from_file_result }}"

    - name: run ssl bootstrap
      shell: >
        /opt/puppetlabs/bin/puppet ssl bootstrap
      register: ssl_bootstrap_result

    - debug: msg="{{ ssl_bootstrap_result }}"

